/*
    SchoolSystem - Read-only production integrity verification
    هذا السكربت للقراءة فقط ولا ينفذ INSERT أو UPDATE أو DELETE.
    شغّله على قاعدة اختبار أو الإنتاج بعد أخذ نسخة احتياطية.
*/
SET NOCOUNT ON;

DECLARE @Results TABLE
(
    CheckName NVARCHAR(200) NOT NULL,
    Result NVARCHAR(20) NOT NULL,
    Details NVARCHAR(1000) NOT NULL
);

/* تحقق من الجداول الأساسية المستخدمة في القيود الجديدة والتقارير. */
INSERT INTO @Results
SELECT N'وجود جدول Students', CASE WHEN OBJECT_ID(N'dbo.Students', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.Students', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END
UNION ALL
SELECT N'وجود جدول StudentClasses', CASE WHEN OBJECT_ID(N'dbo.StudentClasses', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.StudentClasses', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END
UNION ALL
SELECT N'وجود جدول BookBorrowings', CASE WHEN OBJECT_ID(N'dbo.BookBorrowings', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.BookBorrowings', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END
UNION ALL
SELECT N'وجود جدول Fees', CASE WHEN OBJECT_ID(N'dbo.Fees', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.Fees', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END
UNION ALL
SELECT N'وجود جدول FeePlans', CASE WHEN OBJECT_ID(N'dbo.FeePlans', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.FeePlans', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END
UNION ALL
SELECT N'وجود جدول Vouchers', CASE WHEN OBJECT_ID(N'dbo.Vouchers', N'U') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN OBJECT_ID(N'dbo.Vouchers', N'U') IS NULL THEN N'الجدول غير موجود.' ELSE N'الجدول موجود.' END;

/* تحقق من الأعمدة التي تستخدمها الواجهات والخدمات الحالية. */
INSERT INTO @Results
SELECT N'عمود Students.StudentPhone', CASE WHEN COL_LENGTH(N'dbo.Students', N'StudentPhone') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN COL_LENGTH(N'dbo.Students', N'StudentPhone') IS NULL THEN N'الاسم القديم Phone غير مدعوم هنا.' ELSE N'العمود موجود.' END
UNION ALL
SELECT N'عمود Students.Status', CASE WHEN COL_LENGTH(N'dbo.Students', N'Status') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN COL_LENGTH(N'dbo.Students', N'Status') IS NULL THEN N'تعطيل الطالب منطقياً لن يعمل.' ELSE N'العمود موجود.' END
UNION ALL
SELECT N'عمود Vouchers.IsAutoGenerated', CASE WHEN COL_LENGTH(N'dbo.Vouchers', N'IsAutoGenerated') IS NULL THEN N'FAIL' ELSE N'PASS' END,
       CASE WHEN COL_LENGTH(N'dbo.Vouchers', N'IsAutoGenerated') IS NULL THEN N'حماية السندات التلقائية لن تعمل.' ELSE N'العمود موجود.' END;

/* كشف سجلات توزيع يتيمة أو مرتبطة بصفوف غير موجودة. */
IF OBJECT_ID(N'dbo.StudentClasses', N'U') IS NOT NULL AND OBJECT_ID(N'dbo.Students', N'U') IS NOT NULL
BEGIN
    DECLARE @OrphanAssignments INT;
    SELECT @OrphanAssignments = COUNT(*)
    FROM dbo.StudentClasses sc
    LEFT JOIN dbo.Students s ON s.StudentID = sc.StudentID
    LEFT JOIN dbo.Classes c ON c.ClassID = sc.ClassID
    WHERE s.StudentID IS NULL OR c.ClassID IS NULL;

    INSERT INTO @Results VALUES
    (N'توزيعات الطلاب اليتيمة', CASE WHEN @OrphanAssignments = 0 THEN N'PASS' ELSE N'FAIL' END,
     N'عدد السجلات اليتيمة: ' + CONVERT(NVARCHAR(20), @OrphanAssignments));
END;

/* كشف إعارات مرتبطة بكتب غير موجودة. */
IF OBJECT_ID(N'dbo.BookBorrowings', N'U') IS NOT NULL AND OBJECT_ID(N'dbo.Books', N'U') IS NOT NULL
BEGIN
    DECLARE @OrphanBorrowings INT;
    SELECT @OrphanBorrowings = COUNT(*)
    FROM dbo.BookBorrowings br
    LEFT JOIN dbo.Books b ON b.BookID = br.BookID
    WHERE b.BookID IS NULL;

    INSERT INTO @Results VALUES
    (N'إعارات الكتب اليتيمة', CASE WHEN @OrphanBorrowings = 0 THEN N'PASS' ELSE N'FAIL' END,
     N'عدد السجلات اليتيمة: ' + CONVERT(NVARCHAR(20), @OrphanBorrowings));
END;

/* كشف القيم المالية غير المنطقية التي يجب مراجعتها قبل الاستخدام الفعلي. */
IF OBJECT_ID(N'dbo.Fees', N'U') IS NOT NULL
BEGIN
    DECLARE @InvalidFees INT;
    SELECT @InvalidFees = COUNT(*)
    FROM dbo.Fees
    WHERE TotalAmount < 0 OR DiscountAmount < 0 OR PaidAmount < 0
       OR NetAmount < 0 OR RemainingAmount < 0
       OR PaidAmount > NetAmount;

    INSERT INTO @Results VALUES
    (N'سلامة مبالغ الرسوم', CASE WHEN @InvalidFees = 0 THEN N'PASS' ELSE N'FAIL' END,
     N'عدد السجلات غير المنطقية: ' + CONVERT(NVARCHAR(20), @InvalidFees));
END;

SELECT CheckName AS [الفحص], Result AS [النتيجة], Details AS [التفاصيل]
FROM @Results
ORDER BY CASE Result WHEN N'FAIL' THEN 0 ELSE 1 END, CheckName;

IF EXISTS (SELECT 1 FROM @Results WHERE Result = N'FAIL')
    PRINT N'النتيجة العامة: توجد فحوصات فاشلة يجب مراجعتها قبل الإنتاج.';
ELSE
    PRINT N'النتيجة العامة: نجحت فحوصات المخطط وسلامة البيانات المشمولة.';

/*
    اختبارات واجهة مطلوبة بعد تشغيل هذا السكربت:
    1) حاول حذف طالب لديه درجات أو حضور؛ يجب أن يتحول إلى محذوف دون فقدان تاريخه.
    2) حاول حذف حافلة مرتبطة بمسار؛ يجب أن تظهر رسالة منع الحذف.
    3) حاول حذف كتاب لديه إعارة؛ يجب أن تظهر رسالة منع الحذف.
    4) حاول حذف خطة رسوم مستخدمة في رسوم طالب؛ يجب أن تظهر رسالة منع الحذف.
    5) حاول حذف سند IsAutoGenerated = 1؛ يجب أن تظهر رسالة منع الحذف.
    6) تحقق من ظهور العمليات المسموح بها والمرفوضة في سجل الأنشطة عند تسجيلها من الخدمات.
*/
GO

-- ملاحظة: القيود رقم 1 إلى 5 تنفذها خدمات التطبيق داخل C#، وليس هذا السكربت.
-- لا تستخدم هذا الملف بديلاً عن النسخ الاحتياطي أو اختبار الاستعادة.
