/*
    SchoolSystem - Accounting reconciliation verification
    Read-only checks. Execute against SchoolDB before annual closing.
    Every result should be zero unless the record is intentionally legacy and documented.
*/
SET NOCOUNT ON;

/* 1. Fee arithmetic integrity. */
IF OBJECT_ID(N'dbo.Fees', N'U') IS NOT NULL
BEGIN
    SELECT N'Fees: invalid amounts' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Fees
    WHERE TotalAmount < 0 OR DiscountAmount < 0 OR NetAmount < 0
       OR PaidAmount < 0 OR RemainingAmount < 0
       OR DiscountAmount > TotalAmount
       OR PaidAmount > NetAmount;

    SELECT N'Fees: arithmetic mismatch' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Fees
    WHERE ISNULL(NetAmount, 0) <> ISNULL(TotalAmount, 0) - ISNULL(DiscountAmount, 0)
       OR ISNULL(RemainingAmount, 0) <> ISNULL(NetAmount, 0) - ISNULL(PaidAmount, 0);
END;

/* 2. Fee payment vouchers must agree with the fee paid amount. */
IF OBJECT_ID(N'dbo.Fees', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.Vouchers', N'U') IS NOT NULL
BEGIN
    SELECT N'Fees: paid amount differs from receipt vouchers' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Fees f
    OUTER APPLY
    (
        SELECT SUM(ISNULL(v.Amount, 0)) AS VoucherPaid
        FROM dbo.Vouchers v
        WHERE v.ReferenceType IN (N'رسوم', N'Fees', N'Fee')
          AND v.ReferenceID = f.FeeID
          AND v.VoucherType IN (N'قبض', N'Receipt', N'إيصال')
    ) r
    WHERE ABS(ISNULL(f.PaidAmount, 0) - ISNULL(r.VoucherPaid, 0)) > 0.01;

    SELECT N'Auto vouchers: missing reference' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Vouchers v
    WHERE v.IsAutoGenerated = 1
      AND (v.ReferenceType IS NULL OR LTRIM(RTRIM(v.ReferenceType)) = N'' OR v.ReferenceID IS NULL);
END;

/* 3. Expenses must have one matching payment voucher when they are linked to finance. */
IF OBJECT_ID(N'dbo.Expenses', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.Vouchers', N'U') IS NOT NULL
BEGIN
    SELECT N'Expenses: duplicate payment vouchers' AS CheckName, COUNT(*) AS IssueCount
    FROM
    (
        SELECT v.ReferenceID
        FROM dbo.Vouchers v
        WHERE v.ReferenceType IN (N'مصروفات', N'Expenses', N'Expense')
          AND v.ReferenceID IS NOT NULL
        GROUP BY v.ReferenceID
        HAVING COUNT(*) > 1
    ) d;

    SELECT N'Expenses: voucher amount mismatch' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Expenses e
    INNER JOIN dbo.Vouchers v
        ON v.ReferenceID = e.ExpenseID
       AND v.ReferenceType IN (N'مصروفات', N'Expenses', N'Expense')
    WHERE ABS(ISNULL(e.Amount, 0) - ISNULL(v.Amount, 0)) > 0.01;
END;

/* 4. Paid payroll records must have exactly one matching payment voucher. */
IF OBJECT_ID(N'dbo.Payroll', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.Vouchers', N'U') IS NOT NULL
BEGIN
    SELECT N'Payroll: paid records without voucher' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Payroll p
    WHERE p.PaymentDate IS NOT NULL
      AND NOT EXISTS
      (
          SELECT 1 FROM dbo.Vouchers v
          WHERE v.ReferenceType IN (N'رواتب', N'Payroll', N'Salary')
            AND v.ReferenceID = p.PayrollID
      );

    SELECT N'Payroll: duplicate vouchers' AS CheckName, COUNT(*) AS IssueCount
    FROM
    (
        SELECT v.ReferenceID
        FROM dbo.Vouchers v
        WHERE v.ReferenceType IN (N'رواتب', N'Payroll', N'Salary')
          AND v.ReferenceID IS NOT NULL
        GROUP BY v.ReferenceID
        HAVING COUNT(*) > 1
    ) d;

    SELECT N'Payroll: voucher amount mismatch' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Payroll p
    INNER JOIN dbo.Vouchers v
        ON v.ReferenceID = p.PayrollID
       AND v.ReferenceType IN (N'رواتب', N'Payroll', N'Salary')
    WHERE p.PaymentDate IS NOT NULL
      AND ABS(ISNULL(p.NetSalary, 0) - ISNULL(v.Amount, 0)) > 0.01;
END;

/* 5. Voucher quality and duplicate receipt numbers. */
IF OBJECT_ID(N'dbo.Vouchers', N'U') IS NOT NULL
BEGIN
    SELECT N'Vouchers: invalid amounts' AS CheckName, COUNT(*) AS IssueCount
    FROM dbo.Vouchers
    WHERE Amount <= 0;

    SELECT N'Vouchers: duplicate voucher numbers' AS CheckName, COUNT(*) AS IssueCount
    FROM
    (
        SELECT VoucherNumber
        FROM dbo.Vouchers
        WHERE NULLIF(LTRIM(RTRIM(ISNULL(VoucherNumber, N''))), N'') IS NOT NULL
        GROUP BY VoucherNumber
        HAVING COUNT(*) > 1
    ) d;
END;

/* 6. Cash summary for manual reconciliation, not a pass/fail check. */
SELECT N'Cash summary' AS SectionName,
       ISNULL((SELECT SUM(ISNULL(Amount, 0)) FROM dbo.Vouchers WHERE VoucherType IN (N'قبض', N'Receipt', N'إيصال')), 0) AS TotalReceipts,
       ISNULL((SELECT SUM(ISNULL(Amount, 0)) FROM dbo.Vouchers WHERE VoucherType IN (N'صرف', N'Payment', N'Disbursement')), 0) AS TotalDisbursements,
       ISNULL((SELECT SUM(ISNULL(Amount, 0)) FROM dbo.Vouchers WHERE VoucherType IN (N'قبض', N'Receipt', N'إيصال')), 0)
       - ISNULL((SELECT SUM(ISNULL(Amount, 0)) FROM dbo.Vouchers WHERE VoucherType IN (N'صرف', N'Payment', N'Disbursement')), 0) AS NetCashMovement;

PRINT N'اكتمل فحص المطابقة المحاسبية. راجع IssueCount، ويجب معالجة الأخطاء الحرجة قبل الإغلاق السنوي.';
GO
