using System;
using System.Data;
using SchoolSystem.DataAccess;
using SchoolSystem.Models;

namespace SchoolSystem.Services
{
    public class ExpenseService
    {
        private readonly ExpenseRepository expenseRepository;
        private readonly VoucherService voucherService;

        public ExpenseService()
        {
            expenseRepository = new ExpenseRepository();
            voucherService = new VoucherService();
        }

        public DataTable GetAllExpenses()
        {
            return expenseRepository.GetAllExpenses();
        }

        public int AddExpense(Expense expense)
        {
            ValidateExpense(expense);

            if (string.IsNullOrWhiteSpace(expense.ExpenseNumber))
                expense.ExpenseNumber = expenseRepository.GenerateExpenseNumber();

            int expenseId = expenseRepository.AddExpense(expense);

            // إنشاء سند صرف تلقائي عند إضافة المصروف
            voucherService.CreatePaymentVoucherForExpense(
                expense.Amount,
                expense.ExpenseDate,
                string.IsNullOrWhiteSpace(expense.PayeeName) ? "مصروفات مدرسية" : expense.PayeeName,
                expenseId,
                expense.PaymentMethod,
                expense.Description,
                "تم إنشاء سند الصرف تلقائياً من شاشة المصروفات. رقم المصروف: " + expense.ExpenseNumber
            );

            return expenseId;
        }

        public bool UpdateExpense(Expense expense)
        {
            if (expense.ExpenseID <= 0)
                throw new Exception("رقم المصروف غير صحيح.");

            ValidateExpense(expense);

            decimal oldAmount = expenseRepository.GetExpenseAmountById(expense.ExpenseID);
            decimal difference = expense.Amount - oldAmount;

            bool updated = expenseRepository.UpdateExpense(expense);

            if (updated && difference != 0)
            {
                if (difference > 0)
                {
                    // زيادة المصروف: سند صرف بالفرق
                    voucherService.CreatePaymentVoucherForExpense(
                        difference,
                        expense.ExpenseDate,
                        string.IsNullOrWhiteSpace(expense.PayeeName) ? "مصروفات مدرسية" : expense.PayeeName,
                        expense.ExpenseID,
                        expense.PaymentMethod,
                        "فرق زيادة مصروف: " + expense.Description,
                        "تم إنشاء سند صرف فرق تلقائياً بسبب تعديل مبلغ المصروف."
                    );
                }
                else
                {
                    // تخفيض المصروف: سند قبض تسوية بقيمة النقص
                    Voucher correctionVoucher = new Voucher
                    {
                        VoucherType = "قبض",
                        Amount = Math.Abs(difference),
                        VoucherDate = expense.ExpenseDate,
                        PartyName = string.IsNullOrWhiteSpace(expense.PayeeName) ? "تسوية مصروفات" : expense.PayeeName,
                        Description = "تسوية تخفيض مصروف: " + expense.Description,
                        PaymentMethod = expense.PaymentMethod,
                        ReferenceType = "مصروفات",
                        ReferenceID = expense.ExpenseID,
                        Notes = "تم إنشاء سند قبض تسوية تلقائياً بسبب تخفيض مبلغ المصروف.",
                        IsAutoGenerated = true
                    };

                    voucherService.AddVoucher(correctionVoucher);
                }
            }

            return updated;
        }

        public bool DeleteExpense(int expenseId)
        {
            if (expenseId <= 0)
                throw new Exception("رقم المصروف غير صحيح.");

            return expenseRepository.DeleteExpense(expenseId);
        }

        private void ValidateExpense(Expense expense)
        {
            if (expense == null)
                throw new Exception("بيانات المصروف غير موجودة.");

            if (expense.Amount <= 0)
                throw new Exception("مبلغ المصروف يجب أن يكون أكبر من صفر.");

            if (string.IsNullOrWhiteSpace(expense.Category))
                throw new Exception("يجب اختيار فئة المصروف.");

            if (string.IsNullOrWhiteSpace(expense.Description))
                throw new Exception("يجب إدخال بيان المصروف.");
        }
    }
}
