using System;
using System.Data;
using SchoolSystem.DataAccess;
using SchoolSystem.Models;
using SchoolSystem.Security;

namespace SchoolSystem.Services
{
    public class VoucherService
    {
        private readonly VoucherRepository voucherRepository;

        public VoucherService()
        {
            voucherRepository = new VoucherRepository();
        }

        public DataTable GetAllVouchers()
        {
            EnsureCanManageVouchers();
            return voucherRepository.GetAllVouchers();
        }

        public bool AddVoucher(Voucher voucher)
        {
            EnsureCanManageVouchers();
            ValidateVoucher(voucher);

            if (string.IsNullOrWhiteSpace(voucher.VoucherNumber))
                voucher.VoucherNumber = voucherRepository.GenerateVoucherNumber(voucher.VoucherType);

            return voucherRepository.AddVoucher(voucher);
        }

        public bool UpdateVoucher(Voucher voucher)
        {
            EnsureCanManageVouchers();
            if (voucher.VoucherID <= 0)
                throw new Exception("رقم السند غير صحيح.");

            if (voucherRepository.IsAutoGenerated(voucher.VoucherID))
                throw new InvalidOperationException("السند التلقائي للقراءة فقط ولا يمكن تعديله.");

            ValidateVoucher(voucher);

            return voucherRepository.UpdateVoucher(voucher);
        }

        public bool DeleteVoucher(int voucherId)
        {
            EnsureCanManageVouchers();
            if (voucherId <= 0)
                throw new Exception("رقم السند غير صحيح.");

            if (voucherRepository.IsAutoGenerated(voucherId))
                throw new InvalidOperationException("السند التلقائي للقراءة فقط ولا يمكن حذفه.");

            return voucherRepository.DeleteVoucher(voucherId);
        }

        public bool CreateReceiptVoucherForFeePayment(
            decimal amount,
            DateTime voucherDate,
            string studentName,
            int feeId,
            string paymentMethod,
            string notes)
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "قبض",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = studentName,
                Description = "سند قبض رسوم دراسية",
                PaymentMethod = paymentMethod,
                ReferenceType = "رسوم",
                ReferenceID = feeId,
                Notes = notes,
                IsAutoGenerated = true
            };

            return AddVoucher(voucher);
        }

        public bool CreatePaymentVoucherForExpense(
            decimal amount,
            DateTime voucherDate,
            string partyName,
            int expenseId,
            string paymentMethod,
            string description,
            string notes)
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "صرف",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = partyName,
                Description = description,
                PaymentMethod = paymentMethod,
                ReferenceType = "مصروفات",
                ReferenceID = expenseId,
                Notes = notes,
                IsAutoGenerated = true
            };

            return AddVoucher(voucher);
        }

        private static void EnsureCanManageVouchers()
        {
            if (!CurrentUser.HasPermission(PermissionKeys.VouchersManage))
                throw new UnauthorizedAccessException("ليس لديك صلاحية إدارة السندات.");
        }

        private void ValidateVoucher(Voucher voucher)
        {
            if (voucher == null)
                throw new Exception("بيانات السند غير موجودة.");

            if (voucher.VoucherType != "قبض" && voucher.VoucherType != "صرف")
                throw new Exception("نوع السند يجب أن يكون قبض أو صرف.");

            if (voucher.Amount <= 0)
                throw new Exception("مبلغ السند يجب أن يكون أكبر من صفر.");

            if (string.IsNullOrWhiteSpace(voucher.PartyName))
                throw new Exception("يرجى إدخال اسم الطرف.");

            if (string.IsNullOrWhiteSpace(voucher.Description))
                throw new Exception("يرجى إدخال البيان.");

            if (voucher.VoucherDate.Date > DateTime.Today)
                throw new Exception("تاريخ السند لا يمكن أن يكون في المستقبل.");

            if (string.IsNullOrWhiteSpace(voucher.PaymentMethod))
                throw new Exception("يرجى تحديد طريقة الدفع.");

            bool hasReference = voucher.ReferenceID.HasValue && voucher.ReferenceID.Value > 0;
            bool isGeneralReference = string.IsNullOrWhiteSpace(voucher.ReferenceType) || voucher.ReferenceType == "عام";
            if (!isGeneralReference && !hasReference)
                throw new Exception("رقم المرجع مطلوب عند اختيار نوع مرجع مرتبط.");
            if (isGeneralReference && hasReference)
                throw new Exception("لا يمكن استخدام رقم مرجع مع النوع العام.");
            if (voucher.ReferenceID.HasValue && voucher.ReferenceID.Value <= 0)
                throw new Exception("رقم المرجع يجب أن يكون موجبًا.");
        }
    }
}
