using System;
using System.Data;
using SchoolSystem.DataAccess;
using SchoolSystem.Models;
using SchoolSystem.Security;

namespace SchoolSystem.Services
{
    public class VoucherService
    {
        private readonly VoucherRepository voucherRepository;
        private readonly AuditLogService auditLogService = new AuditLogService();

        public VoucherService()
        {
            voucherRepository = new VoucherRepository();
        }

        public DataTable GetAllVouchers()
        {
            CurrentUser.DemandAction("Vouchers", "View", "ليس لديك صلاحية عرض السندات.");
            return voucherRepository.GetAllVouchers();
        }

        public string GenerateVoucherNumber(string voucherType)
        {
            CurrentUser.DemandAction("Vouchers", "Add", "ليس لديك صلاحية توليد رقم سند.");
            if (voucherType != "قبض" && voucherType != "صرف")
                throw new ArgumentException("نوع السند غير صحيح.", "voucherType");

            return voucherRepository.GenerateVoucherNumber(voucherType);
        }

        public bool AddVoucher(Voucher voucher)
        {
            CurrentUser.DemandAction("Vouchers", "Add", "ليس لديك صلاحية إضافة السندات.");
            ValidateVoucher(voucher);

            bool added = voucherRepository.AddVoucher(voucher);
            if (added)
                auditLogService.Record("إنشاء", "Voucher", voucher.VoucherID.ToString(),
                    string.Format("النوع: {0}، الرقم: {1}، المبلغ: {2}، الطرف: {3}", voucher.VoucherType, voucher.VoucherNumber, voucher.Amount, voucher.PartyName));
            return added;
        }

        public bool UpdateVoucher(Voucher voucher)
        {
            CurrentUser.DemandAction("Vouchers", "Edit", "ليس لديك صلاحية تعديل السندات.");
            if (voucher.VoucherID <= 0)
                throw new Exception("رقم السند غير صحيح.");

            if (voucherRepository.IsAutoGenerated(voucher.VoucherID))
                throw new InvalidOperationException("السند التلقائي للقراءة فقط ولا يمكن تعديله.");

            ValidateVoucher(voucher);

            bool updated = voucherRepository.UpdateVoucher(voucher);
            if (updated)
                auditLogService.Record("تعديل", "Voucher", voucher.VoucherID.ToString(),
                    string.Format("النوع: {0}، المبلغ: {1}، الطرف: {2}", voucher.VoucherType, voucher.Amount, voucher.PartyName));
            return updated;
        }

        public bool DeleteVoucher(int voucherId)
        {
            CurrentUser.DemandAction("Vouchers", "Delete", "ليس لديك صلاحية حذف السندات.");
            if (voucherId <= 0)
                throw new Exception("رقم السند غير صحيح.");

            if (voucherRepository.IsAutoGenerated(voucherId))
                throw new InvalidOperationException("السند التلقائي للقراءة فقط ولا يمكن حذفه.");

            bool deleted = voucherRepository.DeleteVoucher(voucherId);
            if (deleted)
                auditLogService.Record("حذف", "Voucher", voucherId.ToString(), "حذف سند يدوي بعد اجتياز التحقق.");
            return deleted;
        }

        public bool CreateReceiptVoucherForFeePayment(
            decimal amount,
            DateTime voucherDate,
            string studentName,
            int feeId,
            string paymentMethod,
            string notes,
            string referenceType = "رسوم")
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "قبض",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = studentName,
                Description = "سند قبض رسوم دراسية",
                PaymentMethod = paymentMethod,
                ReferenceType = string.IsNullOrWhiteSpace(referenceType) ? "رسوم" : referenceType.Trim(),
                ReferenceID = feeId,
                Notes = notes,
                IsAutoGenerated = true
            };

            EnsureCanCreateSystemVoucher(PermissionKeys.FeesManage);
            return AddVoucherCore(voucher);
        }

        public bool CreateReceiptVoucherForExpenseAdjustment(
            decimal amount,
            DateTime voucherDate,
            string partyName,
            int expenseId,
            string paymentMethod,
            string description,
            string notes)
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "قبض",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = partyName,
                Description = description,
                PaymentMethod = paymentMethod,
                ReferenceType = "مصروفات",
                ReferenceID = expenseId,
                Notes = notes,
                IsAutoGenerated = true
            };

            EnsureCanCreateSystemVoucher(PermissionKeys.ExpensesManage);
            return AddVoucherCore(voucher);
        }

        public bool CreatePaymentVoucherForPayroll(
            decimal amount,
            DateTime voucherDate,
            string teacherName,
            int payrollId,
            string paymentMethod,
            int salaryMonth,
            int salaryYear,
            string notes)
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "صرف",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = teacherName,
                Description = "سند صرف راتب عن شهر " + salaryMonth + "/" + salaryYear,
                PaymentMethod = paymentMethod,
                ReferenceType = "رواتب",
                ReferenceID = payrollId,
                Notes = notes,
                IsAutoGenerated = true
            };

            EnsureCanCreateSystemVoucher(PermissionKeys.PayrollManage);
            return AddVoucherCore(voucher);
        }

        public bool CreatePaymentVoucherForExpense(
            decimal amount,
            DateTime voucherDate,
            string partyName,
            int expenseId,
            string paymentMethod,
            string description,
            string notes)
        {
            Voucher voucher = new Voucher
            {
                VoucherType = "صرف",
                Amount = amount,
                VoucherDate = voucherDate,
                PartyName = partyName,
                Description = description,
                PaymentMethod = paymentMethod,
                ReferenceType = "مصروفات",
                ReferenceID = expenseId,
                Notes = notes,
                IsAutoGenerated = true
            };

            EnsureCanCreateSystemVoucher(PermissionKeys.ExpensesManage);
            return AddVoucherCore(voucher);
        }

        private bool AddVoucherCore(Voucher voucher)
        {
            ValidateVoucher(voucher);

            bool added = voucherRepository.AddVoucher(voucher);
            if (added)
                auditLogService.Record("إنشاء", "Voucher", voucher.VoucherID.ToString(),
                    string.Format("سند تلقائي؛ النوع: {0}، الرقم: {1}، المبلغ: {2}، الطرف: {3}", voucher.VoucherType, voucher.VoucherNumber, voucher.Amount, voucher.PartyName));
            return added;
        }

        private static void EnsureCanCreateSystemVoucher(string owningPermission)
        {
            bool canCreate = CurrentUser.CanAdd("Vouchers") || CurrentUser.HasPermission(PermissionKeys.VouchersManage);
            if (owningPermission == PermissionKeys.FeesManage)
                canCreate = canCreate || CurrentUser.CanAdd("Fees") || CurrentUser.HasPermission(PermissionKeys.FeesManage);
            else if (owningPermission == PermissionKeys.ExpensesManage)
                canCreate = canCreate || CurrentUser.CanAdd("Expenses") || CurrentUser.HasPermission(PermissionKeys.ExpensesManage);
            else if (owningPermission == PermissionKeys.PayrollManage)
                canCreate = canCreate || CurrentUser.CanAdd("Payroll") || CurrentUser.HasPermission(PermissionKeys.PayrollManage);

            if (!canCreate)
                throw new UnauthorizedAccessException("ليس لديك صلاحية إنشاء السند التلقائي المرتبط بهذه العملية.");
        }

        private void ValidateVoucher(Voucher voucher)
        {
            if (voucher == null)
                throw new Exception("بيانات السند غير موجودة.");

            if (voucher.VoucherType != "قبض" && voucher.VoucherType != "صرف")
                throw new Exception("نوع السند يجب أن يكون قبض أو صرف.");

            if (voucher.Amount <= 0)
                throw new Exception("مبلغ السند يجب أن يكون أكبر من صفر.");

            if (string.IsNullOrWhiteSpace(voucher.PartyName))
                throw new Exception("يرجى إدخال اسم الطرف.");

            if (string.IsNullOrWhiteSpace(voucher.Description))
                throw new Exception("يرجى إدخال البيان.");

            if (voucher.VoucherDate.Date > DateTime.Today)
                throw new Exception("تاريخ السند لا يمكن أن يكون في المستقبل.");

            if (string.IsNullOrWhiteSpace(voucher.PaymentMethod))
                throw new Exception("يرجى تحديد طريقة الدفع.");

            bool hasReference = voucher.ReferenceID.HasValue && voucher.ReferenceID.Value > 0;
            bool isGeneralReference = string.IsNullOrWhiteSpace(voucher.ReferenceType) || voucher.ReferenceType == "عام";
            if (!isGeneralReference && !hasReference)
                throw new Exception("رقم المرجع مطلوب عند اختيار نوع مرجع مرتبط.");
            if (isGeneralReference && hasReference)
                throw new Exception("لا يمكن استخدام رقم مرجع مع النوع العام.");
            if (voucher.ReferenceID.HasValue && voucher.ReferenceID.Value <= 0)
                throw new Exception("رقم المرجع يجب أن يكون موجبًا.");
        }
    }
}
