using System;
using System.Data;
using System.Data.SqlClient;
using SchoolSystem.Models;

namespace SchoolSystem.DataAccess
{
    public class VoucherRepository
    {
        public DataTable GetAllVouchers()
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = @"
                    SELECT
                        VoucherID,
                        VoucherNumber,
                        VoucherType,
                        Amount,
                        VoucherDate,
                        PartyName,
                        Description,
                        PaymentMethod,
                        ReferenceType,
                        ReferenceID,
                        Notes,
                        IsAutoGenerated,
                        CreatedAt
                    FROM Vouchers
                    ORDER BY VoucherID DESC";

                using (SqlDataAdapter da = new SqlDataAdapter(query, con))
                {
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    return dt;
                }
            }
        }

        public bool AddVoucher(Voucher voucher)
        {
            // الرقم الظاهر في الواجهة مجرد معاينة. الرقم النهائي يجب أن يُولد بعد
            // الحصول على VoucherID داخل نفس عملية الحفظ حتى لا يتكرر مع مستخدم آخر.
            bool needsGeneratedNumber = string.IsNullOrWhiteSpace(voucher.VoucherNumber) ||
                IsGeneratedVoucherNumber(voucher.VoucherNumber, voucher.VoucherType);
            if (needsGeneratedNumber)
                voucher.VoucherNumber = null;

            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = @"
                    IF @VoucherNumber IS NOT NULL AND EXISTS
                    (
                        SELECT 1 FROM Vouchers WITH (UPDLOCK, HOLDLOCK)
                        WHERE VoucherNumber = @VoucherNumber
                    )
                        THROW 51007, N'رقم السند مستخدم مسبقًا؛ أعد توليد الرقم ثم حاول مرة أخرى.', 1;

                    IF @IsAutoGenerated = 1 AND @ReferenceID IS NOT NULL AND EXISTS
                    (
                        SELECT 1 FROM Vouchers WITH (UPDLOCK, HOLDLOCK)
                        WHERE IsAutoGenerated = 1
                          AND VoucherType = @VoucherType
                          AND ReferenceType = @ReferenceType
                          AND ReferenceID = @ReferenceID
                    )
                    BEGIN
                        /*
                           الإنشاء التلقائي idempotent: تحديث الرسوم أو إعادة فتح الشاشة
                           لا يجب أن يفشل بسبب سند موجود؛ نعيد رقم السند الموجود.
                        */
                        SELECT TOP 1 VoucherID
                        FROM Vouchers WITH (UPDLOCK, HOLDLOCK)
                        WHERE IsAutoGenerated = 1
                          AND VoucherType = @VoucherType
                          AND ReferenceType = @ReferenceType
                          AND ReferenceID = @ReferenceID
                        ORDER BY VoucherID DESC;
                        RETURN;
                    END;

                    INSERT INTO Vouchers
                    (
                        VoucherNumber,
                        VoucherType,
                        Amount,
                        VoucherDate,
                        PartyName,
                        Description,
                        PaymentMethod,
                        ReferenceType,
                        ReferenceID,
                        Notes,
                        IsAutoGenerated
                    )
                    VALUES
                    (
                        @VoucherNumber,
                        @VoucherType,
                        @Amount,
                        @VoucherDate,
                        @PartyName,
                        @Description,
                        @PaymentMethod,
                        @ReferenceType,
                        @ReferenceID,
                        @Notes,
                        @IsAutoGenerated
                    );
                    SELECT CAST(SCOPE_IDENTITY() AS INT);";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    AddParameters(cmd, voucher);

                    con.Open();
                    using (SqlTransaction transaction = con.BeginTransaction(IsolationLevel.Serializable))
                    {
                        cmd.Transaction = transaction;
                        object result = cmd.ExecuteScalar();
                        if (result == null || result == DBNull.Value)
                        {
                            transaction.Rollback();
                            return false;
                        }

                        voucher.VoucherID = Convert.ToInt32(result);
                        if (needsGeneratedNumber)
                        {
                            voucher.VoucherNumber = BuildVoucherNumber(voucher.VoucherType, voucher.VoucherDate, voucher.VoucherID);
                            using (SqlCommand numberCommand = new SqlCommand(
                                "UPDATE Vouchers SET VoucherNumber = @VoucherNumber WHERE VoucherID = @VoucherID", con, transaction))
                            {
                                numberCommand.Parameters.AddWithValue("@VoucherNumber", voucher.VoucherNumber);
                                numberCommand.Parameters.AddWithValue("@VoucherID", voucher.VoucherID);
                                numberCommand.ExecuteNonQuery();
                            }
                        }

                        transaction.Commit();
                        return voucher.VoucherID > 0;
                    }
                }
            }
        }

        public bool UpdateVoucher(Voucher voucher)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                const string query = @"
                    IF EXISTS
                    (
                        SELECT 1
                        FROM Vouchers
                        WHERE VoucherID = @VoucherID
                          AND IsAutoGenerated = 1
                    )
                    BEGIN
                        THROW 51006, N'لا يمكن تعديل السند المنشأ تلقائياً لأنه جزء من التسوية المالية.', 1;
                    END;

                    UPDATE Vouchers SET
                        VoucherNumber = @VoucherNumber,
                        VoucherType = @VoucherType,
                        Amount = @Amount,
                        VoucherDate = @VoucherDate,
                        PartyName = @PartyName,
                        Description = @Description,
                        PaymentMethod = @PaymentMethod,
                        ReferenceType = @ReferenceType,
                        ReferenceID = @ReferenceID,
                        Notes = @Notes,
                        IsAutoGenerated = @IsAutoGenerated
                    WHERE VoucherID = @VoucherID
                      AND IsAutoGenerated = 0;";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@VoucherID", voucher.VoucherID);
                    AddParameters(cmd, voucher);

                    con.Open();
                    return cmd.ExecuteNonQuery() > 0;
                }
            }
        }

        public bool IsAutoGenerated(int voucherId)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            using (SqlCommand cmd = new SqlCommand(
                "SELECT IsAutoGenerated FROM Vouchers WHERE VoucherID = @VoucherID", con))
            {
                cmd.Parameters.AddWithValue("@VoucherID", voucherId);
                con.Open();
                object value = cmd.ExecuteScalar();
                return value != null && value != DBNull.Value && Convert.ToBoolean(value);
            }
        }

        public bool DeleteVoucher(int voucherId)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                const string query = @"
                    IF EXISTS
                    (
                        SELECT 1
                        FROM Vouchers
                        WHERE VoucherID = @VoucherID
                          AND IsAutoGenerated = 1
                    )
                        THROW 51004, N'لا يمكن حذف السند المنشأ تلقائياً لأنه جزء من التسوية المالية.', 1;

                    DELETE FROM Vouchers
                    WHERE VoucherID = @VoucherID;";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@VoucherID", voucherId);

                    con.Open();
                    return cmd.ExecuteNonQuery() > 0;
                }
            }
        }

        private string BuildVoucherNumber(string voucherType, DateTime voucherDate, int voucherId)
        {
            string prefix = voucherType == "صرف" ? "PAY" : "REC";
            return prefix + "-" + voucherDate.Year + "-" + voucherId.ToString("00000");
        }

        private bool IsGeneratedVoucherNumber(string voucherNumber, string voucherType)
        {
            if (string.IsNullOrWhiteSpace(voucherNumber))
                return false;

            string prefix = voucherType == "صرف" ? "PAY-" : "REC-";
            return voucherNumber.Trim().StartsWith(prefix, StringComparison.OrdinalIgnoreCase);
        }

        public string GenerateVoucherNumber(string voucherType)
        {
            string prefix = voucherType == "صرف" ? "PAY" : "REC";

            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = "SELECT ISNULL(MAX(VoucherID), 0) + 1 FROM Vouchers";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    con.Open();

                    int nextNumber = Convert.ToInt32(cmd.ExecuteScalar());

                    return prefix + "-" + DateTime.Today.Year + "-" + nextNumber.ToString("00000");
                }
            }
        }

        private void AddParameters(SqlCommand cmd, Voucher voucher)
        {
            cmd.Parameters.AddWithValue(
                "@VoucherNumber",
                string.IsNullOrWhiteSpace(voucher.VoucherNumber)
                    ? (object)DBNull.Value
                    : voucher.VoucherNumber.Trim());
            cmd.Parameters.AddWithValue("@VoucherType", voucher.VoucherType ?? "");
            cmd.Parameters.AddWithValue("@Amount", voucher.Amount);
            cmd.Parameters.AddWithValue("@VoucherDate", voucher.VoucherDate.Date);
            cmd.Parameters.AddWithValue("@PartyName", voucher.PartyName ?? "");
            cmd.Parameters.AddWithValue("@Description", voucher.Description ?? "");

            cmd.Parameters.AddWithValue(
                "@PaymentMethod",
                string.IsNullOrWhiteSpace(voucher.PaymentMethod)
                    ? (object)DBNull.Value
                    : voucher.PaymentMethod
            );

            cmd.Parameters.AddWithValue(
                "@ReferenceType",
                string.IsNullOrWhiteSpace(voucher.ReferenceType)
                    ? (object)DBNull.Value
                    : voucher.ReferenceType
            );

            if (voucher.ReferenceID.HasValue)
                cmd.Parameters.AddWithValue("@ReferenceID", voucher.ReferenceID.Value);
            else
                cmd.Parameters.AddWithValue("@ReferenceID", DBNull.Value);

            cmd.Parameters.AddWithValue(
                "@Notes",
                string.IsNullOrWhiteSpace(voucher.Notes)
                    ? (object)DBNull.Value
                    : voucher.Notes
            );

            cmd.Parameters.AddWithValue("@IsAutoGenerated", voucher.IsAutoGenerated);
        }
    }
}
