using System;
using System.Data;
using System.Data.SqlClient;
using SchoolSystem.Models;

namespace SchoolSystem.DataAccess
{
    public class VoucherRepository
    {
        public DataTable GetAllVouchers()
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = @"
                    SELECT
                        VoucherID,
                        VoucherNumber,
                        VoucherType,
                        Amount,
                        VoucherDate,
                        PartyName,
                        Description,
                        PaymentMethod,
                        ReferenceType,
                        ReferenceID,
                        Notes,
                        IsAutoGenerated,
                        CreatedAt
                    FROM Vouchers
                    ORDER BY VoucherID DESC";

                using (SqlDataAdapter da = new SqlDataAdapter(query, con))
                {
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    return dt;
                }
            }
        }

        public bool AddVoucher(Voucher voucher)
        {
            if (string.IsNullOrWhiteSpace(voucher.VoucherNumber))
                voucher.VoucherNumber = GenerateVoucherNumber(voucher.VoucherType);

            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = @"
                    INSERT INTO Vouchers
                    (
                        VoucherNumber,
                        VoucherType,
                        Amount,
                        VoucherDate,
                        PartyName,
                        Description,
                        PaymentMethod,
                        ReferenceType,
                        ReferenceID,
                        Notes,
                        IsAutoGenerated
                    )
                    VALUES
                    (
                        @VoucherNumber,
                        @VoucherType,
                        @Amount,
                        @VoucherDate,
                        @PartyName,
                        @Description,
                        @PaymentMethod,
                        @ReferenceType,
                        @ReferenceID,
                        @Notes,
                        @IsAutoGenerated
                    );
                    SELECT CAST(SCOPE_IDENTITY() AS INT);";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    AddParameters(cmd, voucher);

                    con.Open();
                    object result = cmd.ExecuteScalar();
                    if (result == null || result == DBNull.Value)
                        return false;
                    voucher.VoucherID = Convert.ToInt32(result);
                    return voucher.VoucherID > 0;
                }
            }
        }

        public bool UpdateVoucher(Voucher voucher)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = @"
                    UPDATE Vouchers SET
                        VoucherNumber = @VoucherNumber,
                        VoucherType = @VoucherType,
                        Amount = @Amount,
                        VoucherDate = @VoucherDate,
                        PartyName = @PartyName,
                        Description = @Description,
                        PaymentMethod = @PaymentMethod,
                        ReferenceType = @ReferenceType,
                        ReferenceID = @ReferenceID,
                        Notes = @Notes,
                        IsAutoGenerated = @IsAutoGenerated
                    WHERE VoucherID = @VoucherID";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@VoucherID", voucher.VoucherID);
                    AddParameters(cmd, voucher);

                    con.Open();
                    return cmd.ExecuteNonQuery() > 0;
                }
            }
        }

        public bool IsAutoGenerated(int voucherId)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            using (SqlCommand cmd = new SqlCommand(
                "SELECT IsAutoGenerated FROM Vouchers WHERE VoucherID = @VoucherID", con))
            {
                cmd.Parameters.AddWithValue("@VoucherID", voucherId);
                con.Open();
                object value = cmd.ExecuteScalar();
                return value != null && value != DBNull.Value && Convert.ToBoolean(value);
            }
        }

        public bool DeleteVoucher(int voucherId)
        {
            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = "DELETE FROM Vouchers WHERE VoucherID = @VoucherID";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Parameters.AddWithValue("@VoucherID", voucherId);

                    con.Open();
                    return cmd.ExecuteNonQuery() > 0;
                }
            }
        }

        public string GenerateVoucherNumber(string voucherType)
        {
            string prefix = voucherType == "صرف" ? "PAY" : "REC";

            using (SqlConnection con = DbConnection.GetConnection())
            {
                string query = "SELECT ISNULL(MAX(VoucherID), 0) + 1 FROM Vouchers";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    con.Open();

                    int nextNumber = Convert.ToInt32(cmd.ExecuteScalar());

                    return prefix + "-" + DateTime.Today.Year + "-" + nextNumber.ToString("00000");
                }
            }
        }

        private void AddParameters(SqlCommand cmd, Voucher voucher)
        {
            cmd.Parameters.AddWithValue("@VoucherNumber", voucher.VoucherNumber ?? "");
            cmd.Parameters.AddWithValue("@VoucherType", voucher.VoucherType ?? "");
            cmd.Parameters.AddWithValue("@Amount", voucher.Amount);
            cmd.Parameters.AddWithValue("@VoucherDate", voucher.VoucherDate.Date);
            cmd.Parameters.AddWithValue("@PartyName", voucher.PartyName ?? "");
            cmd.Parameters.AddWithValue("@Description", voucher.Description ?? "");

            cmd.Parameters.AddWithValue(
                "@PaymentMethod",
                string.IsNullOrWhiteSpace(voucher.PaymentMethod)
                    ? (object)DBNull.Value
                    : voucher.PaymentMethod
            );

            cmd.Parameters.AddWithValue(
                "@ReferenceType",
                string.IsNullOrWhiteSpace(voucher.ReferenceType)
                    ? (object)DBNull.Value
                    : voucher.ReferenceType
            );

            if (voucher.ReferenceID.HasValue)
                cmd.Parameters.AddWithValue("@ReferenceID", voucher.ReferenceID.Value);
            else
                cmd.Parameters.AddWithValue("@ReferenceID", DBNull.Value);

            cmd.Parameters.AddWithValue(
                "@Notes",
                string.IsNullOrWhiteSpace(voucher.Notes)
                    ? (object)DBNull.Value
                    : voucher.Notes
            );

            cmd.Parameters.AddWithValue("@IsAutoGenerated", voucher.IsAutoGenerated);
        }
    }
}
