using System;
using System.Data;
using System.Globalization;
using System.Threading.Tasks;
using System.Windows.Forms;
using SchoolSystem.Models;
using SchoolSystem.Helpers;
using SchoolSystem.Services;

namespace SchoolSystem.UI
{
    public partial class VouchersForm : UserControl
    {
        private readonly VoucherService voucherService = new VoucherService();

        private int selectedVoucherId = 0;
        private DataTable allVouchers;
        private bool isLoading = false;

        public VouchersForm()
        {
            InitializeComponent();
            Dock = DockStyle.Fill;
            Load += VouchersForm_Load;
        }

        private async void VouchersForm_Load(object sender, EventArgs e)
        {
            try
            {
                isLoading = true;

                InitializeLookups();

                dtpVoucherDate.Value = DateTime.Today;

                await LoadVouchersAsync();

                ClearInputs();
            }
            catch (Exception ex)
            {
                MessageBox.Show("حدث خطأ أثناء تحميل السندات:\n" + ex.Message);
            }
            finally
            {
                isLoading = false;
            }
        }

        private void InitializeLookups()
        {
            cmbVoucherType.Items.Clear();
            cmbVoucherType.Items.AddRange(new object[] { "قبض", "صرف" });
            cmbVoucherType.SelectedIndex = 0;

            cmbPaymentMethod.Items.Clear();
            cmbPaymentMethod.Items.AddRange(new object[] { "نقداً", "حوالة", "شيك", "محفظة إلكترونية", "أخرى" });
            cmbPaymentMethod.SelectedIndex = 0;

            cmbReferenceType.Items.Clear();
            cmbReferenceType.Items.AddRange(new object[] { "عام", "رسوم", "مصروفات", "رواتب", "نقل", "مكتبة" });
            cmbReferenceType.SelectedIndex = 0;

            cmbFilterType.Items.Clear();
            cmbFilterType.Items.AddRange(new object[] { "كل السندات", "قبض", "صرف" });
            cmbFilterType.SelectedIndex = 0;
        }

        private async Task LoadVouchersAsync()
        {
            try
            {
                Cursor = Cursors.WaitCursor;

                allVouchers = await Task.Run(() => voucherService.GetAllVouchers());

                ApplyFilter();
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }

        private void ApplyFilter()
        {
            if (allVouchers == null)
                return;

            DataView dv = allVouchers.DefaultView;

            string searchText = UIHelper.EscapeDataViewFilterValue(txtSearch.Text);
            string selectedType = cmbFilterType.SelectedItem == null
                ? "كل السندات"
                : cmbFilterType.SelectedItem.ToString();

            string filter = "";

            if (!string.IsNullOrWhiteSpace(searchText))
            {
                filter =
                    "(VoucherNumber LIKE '%" + searchText + "%' " +
                    "OR VoucherType LIKE '%" + searchText + "%' " +
                    "OR PartyName LIKE '%" + searchText + "%' " +
                    "OR Description LIKE '%" + searchText + "%' " +
                    "OR PaymentMethod LIKE '%" + searchText + "%' " +
                    "OR ReferenceType LIKE '%" + searchText + "%' " +
                    "OR Notes LIKE '%" + searchText + "%')";
            }

            if (selectedType != "كل السندات")
            {
                if (!string.IsNullOrWhiteSpace(filter))
                    filter += " AND ";

                filter += "VoucherType = '" + UIHelper.EscapeDataViewFilterValue(selectedType) + "'";
            }

            dv.RowFilter = filter;

            dataGridViewVouchers.DataSource = dv;

            lblRecordCount.Text = "عدد السندات: " + dv.Count;

            FormatGrid();
        }

        private string EscapeFilter(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "";

            return value
                .Replace("'", "''")
                .Replace("[", "[[]")
                .Replace("%", "[%]")
                .Replace("*", "[*]");
        }

        private void FormatGrid()
        {
            if (dataGridViewVouchers.Columns.Count == 0)
                return;

            HideColumn("VoucherID");
            HideColumn("ReferenceID");

            SetHeader("VoucherNumber", "رقم السند");
            SetHeader("VoucherType", "النوع");
            SetHeader("Amount", "المبلغ");
            SetHeader("VoucherDate", "التاريخ");
            SetHeader("PartyName", "الطرف");
            SetHeader("Description", "البيان");
            SetHeader("PaymentMethod", "طريقة الدفع");
            SetHeader("ReferenceType", "المرجع");
            SetHeader("Notes", "ملاحظات");
            SetHeader("IsAutoGenerated", "تلقائي");
            SetHeader("CreatedAt", "تاريخ الإدخال");

            FormatMoney("Amount");
            FormatDate("VoucherDate");
            FormatDate("CreatedAt");

            dataGridViewVouchers.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void HideColumn(string columnName)
        {
            if (dataGridViewVouchers.Columns.Contains(columnName))
                dataGridViewVouchers.Columns[columnName].Visible = false;
        }

        private void SetHeader(string columnName, string headerText)
        {
            if (dataGridViewVouchers.Columns.Contains(columnName))
                dataGridViewVouchers.Columns[columnName].HeaderText = headerText;
        }

        private void FormatMoney(string columnName)
        {
            if (dataGridViewVouchers.Columns.Contains(columnName))
                dataGridViewVouchers.Columns[columnName].DefaultCellStyle.Format = "N2";
        }

        private void FormatDate(string columnName)
        {
            if (dataGridViewVouchers.Columns.Contains(columnName))
                dataGridViewVouchers.Columns[columnName].DefaultCellStyle.Format = "dd/MM/yyyy";
        }

        private void FilterControls_Changed(object sender, EventArgs e)
        {
            if (!isLoading)
                ApplyFilter();
        }

        private void ClearInputs()
        {
            selectedVoucherId = 0;

            txtVoucherNumber.Clear();

            if (cmbVoucherType.Items.Count > 0)
                cmbVoucherType.SelectedIndex = 0;

            txtAmount.Text = "0";

            dtpVoucherDate.Value = DateTime.Today;

            txtPartyName.Clear();
            txtDescription.Clear();

            if (cmbPaymentMethod.Items.Count > 0)
                cmbPaymentMethod.SelectedIndex = 0;

            if (cmbReferenceType.Items.Count > 0)
                cmbReferenceType.SelectedIndex = 0;

            txtReferenceID.Clear();

            chkIsAutoGenerated.Checked = false;
            chkIsAutoGenerated.Enabled = true;

            txtNotes.Clear();
        }

        private bool ValidateInputs()
        {
            if (cmbVoucherType.SelectedItem == null)
            {
                MessageBox.Show("اختر نوع السند.");
                cmbVoucherType.Focus();
                return false;
            }

            decimal amount = ReadDecimal(txtAmount.Text);

            if (amount <= 0)
            {
                MessageBox.Show("أدخل مبلغاً صحيحاً أكبر من صفر.");
                txtAmount.Focus();
                return false;
            }

            if (string.IsNullOrWhiteSpace(txtPartyName.Text))
            {
                MessageBox.Show("أدخل اسم الطرف.");
                txtPartyName.Focus();
                return false;
            }

            if (string.IsNullOrWhiteSpace(txtDescription.Text))
            {
                MessageBox.Show("أدخل بيان السند.");
                txtDescription.Focus();
                return false;
            }

            if (!string.IsNullOrWhiteSpace(txtReferenceID.Text))
            {
                int temp;
                if (!int.TryParse(txtReferenceID.Text.Trim(), out temp))
                {
                    MessageBox.Show("رقم المرجع يجب أن يكون رقماً صحيحاً.");
                    txtReferenceID.Focus();
                    return false;
                }
            }

            return true;
        }

        private decimal ReadDecimal(string text)
        {
            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.CurrentCulture, out decimal value))
                return value;

            if (decimal.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out value))
                return value;

            return 0;
        }

        private int? ReadNullableInt(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                return null;

            if (int.TryParse(text.Trim(), out int value))
                return value;

            return null;
        }

        private Voucher GetVoucherFromInputs()
        {
            return new Voucher
            {
                VoucherID = selectedVoucherId,
                VoucherNumber = txtVoucherNumber.Text.Trim(),
                VoucherType = cmbVoucherType.Text.Trim(),

                Amount = ReadDecimal(txtAmount.Text),
                VoucherDate = dtpVoucherDate.Value.Date,

                PartyName = txtPartyName.Text.Trim(),
                Description = txtDescription.Text.Trim(),

                PaymentMethod = cmbPaymentMethod.Text.Trim(),

                ReferenceType = cmbReferenceType.Text.Trim(),
                ReferenceID = ReadNullableInt(txtReferenceID.Text),

                Notes = txtNotes.Text.Trim(),

                IsAutoGenerated = chkIsAutoGenerated.Checked
            };
        }

        private void dataGridViewVouchers_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0 || dataGridViewVouchers.Rows.Count == 0)
                return;

            DataRowView rowView = dataGridViewVouchers.Rows[e.RowIndex].DataBoundItem as DataRowView;

            if (rowView != null)
                FillFieldsFromRow(rowView.Row);
        }

        private void FillFieldsFromRow(DataRow row)
        {
            selectedVoucherId = Convert.ToInt32(row["VoucherID"]);

            txtVoucherNumber.Text = row["VoucherNumber"] == DBNull.Value ? "" : row["VoucherNumber"].ToString();
            cmbVoucherType.Text = row["VoucherType"].ToString();

            txtAmount.Text = Convert.ToDecimal(row["Amount"]).ToString("N2");

            dtpVoucherDate.Value = Convert.ToDateTime(row["VoucherDate"]);

            txtPartyName.Text = row["PartyName"] == DBNull.Value ? "" : row["PartyName"].ToString();
            txtDescription.Text = row["Description"] == DBNull.Value ? "" : row["Description"].ToString();

            cmbPaymentMethod.Text = row["PaymentMethod"] == DBNull.Value ? "" : row["PaymentMethod"].ToString();
            cmbReferenceType.Text = row["ReferenceType"] == DBNull.Value ? "عام" : row["ReferenceType"].ToString();

            txtReferenceID.Text = row["ReferenceID"] == DBNull.Value ? "" : row["ReferenceID"].ToString();

            txtNotes.Text = row["Notes"] == DBNull.Value ? "" : row["Notes"].ToString();

            chkIsAutoGenerated.Checked = row["IsAutoGenerated"] != DBNull.Value && Convert.ToBoolean(row["IsAutoGenerated"]);
        }

        private async void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                if (!ValidateInputs())
                    return;

                Voucher voucher = GetVoucherFromInputs();

                await Task.Run(() => voucherService.AddVoucher(voucher));

                MessageBox.Show("تمت إضافة السند بنجاح.");

                await LoadVouchersAsync();
                ClearInputs();
            }
            catch (Exception ex)
            {
                MessageBox.Show("فشل إضافة السند:\n" + ex.Message);
            }
        }

        private async void btnUpdate_Click(object sender, EventArgs e)
        {
            try
            {
                if (selectedVoucherId == 0)
                {
                    MessageBox.Show("اختر سنداً من الجدول أولاً.");
                    return;
                }

                if (!ValidateInputs())
                    return;

                Voucher voucher = GetVoucherFromInputs();

                bool result = await Task.Run(() => voucherService.UpdateVoucher(voucher));

                MessageBox.Show(result ? "تم تعديل السند بنجاح." : "لم يتم تعديل السند.");

                await LoadVouchersAsync();
                ClearInputs();
            }
            catch (Exception ex)
            {
                MessageBox.Show("فشل تعديل السند:\n" + ex.Message);
            }
        }

        private async void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (selectedVoucherId == 0)
                {
                    MessageBox.Show("اختر سنداً من الجدول أولاً.");
                    return;
                }

                DialogResult confirm = MessageBox.Show(
                    "هل تريد حذف السند المحدد؟",
                    "تأكيد الحذف",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question);

                if (confirm != DialogResult.Yes)
                    return;

                bool result = await Task.Run(() => voucherService.DeleteVoucher(selectedVoucherId));

                MessageBox.Show(result ? "تم حذف السند بنجاح." : "لم يتم حذف السند.");

                await LoadVouchersAsync();
                ClearInputs();
            }
            catch (Exception ex)
            {
                MessageBox.Show("فشل حذف السند:\n" + ex.Message);
            }
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearInputs();
        }
    }
}
