namespace SchoolSystem.UI
{
    partial class VouchersForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            this.panelTitle = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panelFields = new System.Windows.Forms.Panel();
            this.tableLayoutFields = new System.Windows.Forms.TableLayoutPanel();
            this.lblVoucherNumber = new System.Windows.Forms.Label();
            this.txtVoucherNumber = new System.Windows.Forms.TextBox();
            this.lblVoucherType = new System.Windows.Forms.Label();
            this.cmbVoucherType = new System.Windows.Forms.ComboBox();
            this.lblAmount = new System.Windows.Forms.Label();
            this.txtAmount = new System.Windows.Forms.TextBox();
            this.lblVoucherDate = new System.Windows.Forms.Label();
            this.dtpVoucherDate = new System.Windows.Forms.DateTimePicker();
            this.lblPartyName = new System.Windows.Forms.Label();
            this.txtPartyName = new System.Windows.Forms.TextBox();
            this.lblDescription = new System.Windows.Forms.Label();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.lblPaymentMethod = new System.Windows.Forms.Label();
            this.cmbPaymentMethod = new System.Windows.Forms.ComboBox();
            this.lblReferenceType = new System.Windows.Forms.Label();
            this.cmbReferenceType = new System.Windows.Forms.ComboBox();
            this.lblReferenceID = new System.Windows.Forms.Label();
            this.txtReferenceID = new System.Windows.Forms.TextBox();
            this.lblIsAutoGenerated = new System.Windows.Forms.Label();
            this.chkIsAutoGenerated = new System.Windows.Forms.CheckBox();
            this.lblNotes = new System.Windows.Forms.Label();
            this.txtNotes = new System.Windows.Forms.TextBox();
            this.panelButtons = new System.Windows.Forms.Panel();
            this.btnAdd = new System.Windows.Forms.Button();
            this.btnUpdate = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.btnClear = new System.Windows.Forms.Button();
            this.panelSearch = new System.Windows.Forms.Panel();
            this.lblSearch = new System.Windows.Forms.Label();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.cmbFilterType = new System.Windows.Forms.ComboBox();
            this.dataGridViewVouchers = new System.Windows.Forms.DataGridView();
            this.panelBottom = new System.Windows.Forms.Panel();
            this.lblRecordCount = new System.Windows.Forms.Label();
            this.panelTitle.SuspendLayout();
            this.panelFields.SuspendLayout();
            this.tableLayoutFields.SuspendLayout();
            this.panelButtons.SuspendLayout();
            this.panelSearch.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewVouchers)).BeginInit();
            this.panelBottom.SuspendLayout();
            this.SuspendLayout();
            // 
            // panelTitle
            // 
            this.panelTitle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            this.panelTitle.Controls.Add(this.lblTitle);
            this.panelTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTitle.Location = new System.Drawing.Point(0, 0);
            this.panelTitle.Name = "panelTitle";
            this.panelTitle.Size = new System.Drawing.Size(1100, 55);
            this.panelTitle.TabIndex = 0;
            // 
            // lblTitle
            // 
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("Tahoma", 15F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(1100, 55);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "إدارة السندات المالية - قبض / صرف";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panelFields
            // 
            this.panelFields.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(250)))));
            this.panelFields.Controls.Add(this.tableLayoutFields);
            this.panelFields.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelFields.Location = new System.Drawing.Point(0, 55);
            this.panelFields.Name = "panelFields";
            this.panelFields.Padding = new System.Windows.Forms.Padding(15);
            this.panelFields.Size = new System.Drawing.Size(1100, 260);
            this.panelFields.TabIndex = 1;
            // 
            // tableLayoutFields
            // 
            this.tableLayoutFields.ColumnCount = 4;
            this.tableLayoutFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 130F));
            this.tableLayoutFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 130F));
            this.tableLayoutFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutFields.Controls.Add(this.lblVoucherNumber, 0, 0);
            this.tableLayoutFields.Controls.Add(this.txtVoucherNumber, 1, 0);
            this.tableLayoutFields.Controls.Add(this.lblVoucherType, 2, 0);
            this.tableLayoutFields.Controls.Add(this.cmbVoucherType, 3, 0);
            this.tableLayoutFields.Controls.Add(this.lblAmount, 0, 1);
            this.tableLayoutFields.Controls.Add(this.txtAmount, 1, 1);
            this.tableLayoutFields.Controls.Add(this.lblVoucherDate, 2, 1);
            this.tableLayoutFields.Controls.Add(this.dtpVoucherDate, 3, 1);
            this.tableLayoutFields.Controls.Add(this.lblPartyName, 0, 2);
            this.tableLayoutFields.Controls.Add(this.txtPartyName, 1, 2);
            this.tableLayoutFields.Controls.Add(this.lblDescription, 2, 2);
            this.tableLayoutFields.Controls.Add(this.txtDescription, 3, 2);
            this.tableLayoutFields.Controls.Add(this.lblPaymentMethod, 0, 3);
            this.tableLayoutFields.Controls.Add(this.cmbPaymentMethod, 1, 3);
            this.tableLayoutFields.Controls.Add(this.lblReferenceType, 2, 3);
            this.tableLayoutFields.Controls.Add(this.cmbReferenceType, 3, 3);
            this.tableLayoutFields.Controls.Add(this.lblReferenceID, 0, 4);
            this.tableLayoutFields.Controls.Add(this.txtReferenceID, 1, 4);
            this.tableLayoutFields.Controls.Add(this.lblIsAutoGenerated, 2, 4);
            this.tableLayoutFields.Controls.Add(this.chkIsAutoGenerated, 3, 4);
            this.tableLayoutFields.Controls.Add(this.lblNotes, 0, 5);
            this.tableLayoutFields.Controls.Add(this.txtNotes, 1, 5);
            this.tableLayoutFields.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutFields.Location = new System.Drawing.Point(15, 15);
            this.tableLayoutFields.Name = "tableLayoutFields";
            this.tableLayoutFields.RowCount = 6;
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tableLayoutFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.tableLayoutFields.Size = new System.Drawing.Size(1070, 230);
            this.tableLayoutFields.TabIndex = 0;
            // 
            // lblVoucherNumber
            // 
            this.lblVoucherNumber.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVoucherNumber.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblVoucherNumber.Location = new System.Drawing.Point(943, 0);
            this.lblVoucherNumber.Name = "lblVoucherNumber";
            this.lblVoucherNumber.Size = new System.Drawing.Size(124, 38);
            this.lblVoucherNumber.TabIndex = 0;
            this.lblVoucherNumber.Text = "رقم السند:";
            this.lblVoucherNumber.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtVoucherNumber
            // 
            this.txtVoucherNumber.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(245)))), ((int)(((byte)(251)))));
            this.txtVoucherNumber.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtVoucherNumber.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtVoucherNumber.Location = new System.Drawing.Point(538, 3);
            this.txtVoucherNumber.Name = "txtVoucherNumber";
            this.txtVoucherNumber.ReadOnly = true;
            this.txtVoucherNumber.Size = new System.Drawing.Size(399, 27);
            this.txtVoucherNumber.TabIndex = 1;
            // 
            // lblVoucherType
            // 
            this.lblVoucherType.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVoucherType.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblVoucherType.Location = new System.Drawing.Point(408, 0);
            this.lblVoucherType.Name = "lblVoucherType";
            this.lblVoucherType.Size = new System.Drawing.Size(124, 38);
            this.lblVoucherType.TabIndex = 2;
            this.lblVoucherType.Text = "نوع السند:";
            this.lblVoucherType.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cmbVoucherType
            // 
            this.cmbVoucherType.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbVoucherType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbVoucherType.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.cmbVoucherType.Location = new System.Drawing.Point(3, 3);
            this.cmbVoucherType.Name = "cmbVoucherType";
            this.cmbVoucherType.Size = new System.Drawing.Size(399, 27);
            this.cmbVoucherType.TabIndex = 3;
            // 
            // lblAmount
            // 
            this.lblAmount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAmount.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblAmount.Location = new System.Drawing.Point(943, 38);
            this.lblAmount.Name = "lblAmount";
            this.lblAmount.Size = new System.Drawing.Size(124, 38);
            this.lblAmount.TabIndex = 4;
            this.lblAmount.Text = "المبلغ:";
            this.lblAmount.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtAmount
            // 
            this.txtAmount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtAmount.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtAmount.Location = new System.Drawing.Point(538, 41);
            this.txtAmount.Name = "txtAmount";
            this.txtAmount.Size = new System.Drawing.Size(399, 27);
            this.txtAmount.TabIndex = 5;
            this.txtAmount.Text = "0";
            // 
            // lblVoucherDate
            // 
            this.lblVoucherDate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVoucherDate.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblVoucherDate.Location = new System.Drawing.Point(408, 38);
            this.lblVoucherDate.Name = "lblVoucherDate";
            this.lblVoucherDate.Size = new System.Drawing.Size(124, 38);
            this.lblVoucherDate.TabIndex = 6;
            this.lblVoucherDate.Text = "تاريخ السند:";
            this.lblVoucherDate.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // dtpVoucherDate
            // 
            this.dtpVoucherDate.CustomFormat = "dd/MM/yyyy";
            this.dtpVoucherDate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtpVoucherDate.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.dtpVoucherDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpVoucherDate.Location = new System.Drawing.Point(3, 41);
            this.dtpVoucherDate.Name = "dtpVoucherDate";
            this.dtpVoucherDate.Size = new System.Drawing.Size(399, 27);
            this.dtpVoucherDate.TabIndex = 7;
            // 
            // lblPartyName
            // 
            this.lblPartyName.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPartyName.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblPartyName.Location = new System.Drawing.Point(943, 76);
            this.lblPartyName.Name = "lblPartyName";
            this.lblPartyName.Size = new System.Drawing.Size(124, 38);
            this.lblPartyName.TabIndex = 8;
            this.lblPartyName.Text = "الطرف:";
            this.lblPartyName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtPartyName
            // 
            this.txtPartyName.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtPartyName.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtPartyName.Location = new System.Drawing.Point(538, 79);
            this.txtPartyName.Name = "txtPartyName";
            this.txtPartyName.Size = new System.Drawing.Size(399, 27);
            this.txtPartyName.TabIndex = 9;
            // 
            // lblDescription
            // 
            this.lblDescription.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDescription.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblDescription.Location = new System.Drawing.Point(408, 76);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new System.Drawing.Size(124, 38);
            this.lblDescription.TabIndex = 10;
            this.lblDescription.Text = "البيان:";
            this.lblDescription.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtDescription
            // 
            this.txtDescription.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtDescription.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtDescription.Location = new System.Drawing.Point(3, 79);
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Size = new System.Drawing.Size(399, 27);
            this.txtDescription.TabIndex = 11;
            // 
            // lblPaymentMethod
            // 
            this.lblPaymentMethod.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPaymentMethod.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblPaymentMethod.Location = new System.Drawing.Point(943, 114);
            this.lblPaymentMethod.Name = "lblPaymentMethod";
            this.lblPaymentMethod.Size = new System.Drawing.Size(124, 38);
            this.lblPaymentMethod.TabIndex = 12;
            this.lblPaymentMethod.Text = "طريقة الدفع:";
            this.lblPaymentMethod.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cmbPaymentMethod
            // 
            this.cmbPaymentMethod.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbPaymentMethod.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPaymentMethod.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.cmbPaymentMethod.Location = new System.Drawing.Point(538, 117);
            this.cmbPaymentMethod.Name = "cmbPaymentMethod";
            this.cmbPaymentMethod.Size = new System.Drawing.Size(399, 27);
            this.cmbPaymentMethod.TabIndex = 13;
            // 
            // lblReferenceType
            // 
            this.lblReferenceType.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblReferenceType.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblReferenceType.Location = new System.Drawing.Point(408, 114);
            this.lblReferenceType.Name = "lblReferenceType";
            this.lblReferenceType.Size = new System.Drawing.Size(124, 38);
            this.lblReferenceType.TabIndex = 14;
            this.lblReferenceType.Text = "المرجع:";
            this.lblReferenceType.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cmbReferenceType
            // 
            this.cmbReferenceType.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbReferenceType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbReferenceType.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.cmbReferenceType.Location = new System.Drawing.Point(3, 117);
            this.cmbReferenceType.Name = "cmbReferenceType";
            this.cmbReferenceType.Size = new System.Drawing.Size(399, 27);
            this.cmbReferenceType.TabIndex = 15;
            // 
            // lblReferenceID
            // 
            this.lblReferenceID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblReferenceID.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblReferenceID.Location = new System.Drawing.Point(943, 152);
            this.lblReferenceID.Name = "lblReferenceID";
            this.lblReferenceID.Size = new System.Drawing.Size(124, 38);
            this.lblReferenceID.TabIndex = 16;
            this.lblReferenceID.Text = "رقم المرجع:";
            this.lblReferenceID.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtReferenceID
            // 
            this.txtReferenceID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtReferenceID.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtReferenceID.Location = new System.Drawing.Point(538, 155);
            this.txtReferenceID.Name = "txtReferenceID";
            this.txtReferenceID.Size = new System.Drawing.Size(399, 27);
            this.txtReferenceID.TabIndex = 17;
            // 
            // lblIsAutoGenerated
            // 
            this.lblIsAutoGenerated.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIsAutoGenerated.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblIsAutoGenerated.Location = new System.Drawing.Point(408, 152);
            this.lblIsAutoGenerated.Name = "lblIsAutoGenerated";
            this.lblIsAutoGenerated.Size = new System.Drawing.Size(124, 38);
            this.lblIsAutoGenerated.TabIndex = 18;
            this.lblIsAutoGenerated.Text = "تلقائي؟";
            this.lblIsAutoGenerated.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // chkIsAutoGenerated
            // 
            this.chkIsAutoGenerated.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkIsAutoGenerated.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.chkIsAutoGenerated.Location = new System.Drawing.Point(3, 155);
            this.chkIsAutoGenerated.Name = "chkIsAutoGenerated";
            this.chkIsAutoGenerated.Size = new System.Drawing.Size(399, 32);
            this.chkIsAutoGenerated.TabIndex = 19;
            this.chkIsAutoGenerated.Text = "تم إنشاء السند تلقائياً من شاشة أخرى";
            this.chkIsAutoGenerated.UseVisualStyleBackColor = true;
            // 
            // lblNotes
            // 
            this.lblNotes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNotes.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.lblNotes.Location = new System.Drawing.Point(943, 190);
            this.lblNotes.Name = "lblNotes";
            this.lblNotes.Size = new System.Drawing.Size(124, 42);
            this.lblNotes.TabIndex = 20;
            this.lblNotes.Text = "ملاحظات:";
            this.lblNotes.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtNotes
            // 
            this.tableLayoutFields.SetColumnSpan(this.txtNotes, 3);
            this.txtNotes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNotes.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.txtNotes.Location = new System.Drawing.Point(3, 193);
            this.txtNotes.Name = "txtNotes";
            this.txtNotes.Size = new System.Drawing.Size(934, 27);
            this.txtNotes.TabIndex = 21;
            // 
            // panelButtons
            // 
            this.panelButtons.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(250)))));
            this.panelButtons.Controls.Add(this.btnAdd);
            this.panelButtons.Controls.Add(this.btnUpdate);
            this.panelButtons.Controls.Add(this.btnDelete);
            this.panelButtons.Controls.Add(this.btnClear);
            this.panelButtons.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelButtons.Location = new System.Drawing.Point(0, 315);
            this.panelButtons.Name = "panelButtons";
            this.panelButtons.Size = new System.Drawing.Size(1100, 55);
            this.panelButtons.TabIndex = 2;
            // 
            // btnAdd
            // 
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(174)))), ((int)(((byte)(96)))));
            this.btnAdd.FlatAppearance.BorderSize = 0;
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            this.btnAdd.Location = new System.Drawing.Point(970, 10);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(115, 35);
            this.btnAdd.TabIndex = 0;
            this.btnAdd.Text = "إضافة";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // btnUpdate
            // 
            this.btnUpdate.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(126)))), ((int)(((byte)(34)))));
            this.btnUpdate.FlatAppearance.BorderSize = 0;
            this.btnUpdate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnUpdate.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.Location = new System.Drawing.Point(845, 10);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new System.Drawing.Size(115, 35);
            this.btnUpdate.TabIndex = 1;
            this.btnUpdate.Text = "تعديل";
            this.btnUpdate.UseVisualStyleBackColor = false;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(57)))), ((int)(((byte)(43)))));
            this.btnDelete.FlatAppearance.BorderSize = 0;
            this.btnDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDelete.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.Location = new System.Drawing.Point(720, 10);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(115, 35);
            this.btnDelete.TabIndex = 2;
            this.btnDelete.Text = "حذف";
            this.btnDelete.UseVisualStyleBackColor = false;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnClear
            // 
            this.btnClear.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(140)))), ((int)(((byte)(141)))));
            this.btnClear.FlatAppearance.BorderSize = 0;
            this.btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClear.Font = new System.Drawing.Font("Tahoma", 10F, System.Drawing.FontStyle.Bold);
            this.btnClear.ForeColor = System.Drawing.Color.White;
            this.btnClear.Location = new System.Drawing.Point(595, 10);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new System.Drawing.Size(115, 35);
            this.btnClear.TabIndex = 3;
            this.btnClear.Text = "تفريغ";
            this.btnClear.UseVisualStyleBackColor = false;
            this.btnClear.Click += new System.EventHandler(this.btnClear_Click);
            // 
            // panelSearch
            // 
            this.panelSearch.BackColor = System.Drawing.Color.White;
            this.panelSearch.Controls.Add(this.lblSearch);
            this.panelSearch.Controls.Add(this.txtSearch);
            this.panelSearch.Controls.Add(this.cmbFilterType);
            this.panelSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelSearch.Location = new System.Drawing.Point(0, 370);
            this.panelSearch.Name = "panelSearch";
            this.panelSearch.Size = new System.Drawing.Size(1100, 45);
            this.panelSearch.TabIndex = 3;
            // 
            // lblSearch
            // 
            this.lblSearch.Font = new System.Drawing.Font("Tahoma", 10F);
            this.lblSearch.Location = new System.Drawing.Point(970, 10);
            this.lblSearch.Name = "lblSearch";
            this.lblSearch.Size = new System.Drawing.Size(110, 25);
            this.lblSearch.TabIndex = 0;
            this.lblSearch.Text = "بحث / تصفية:";
            this.lblSearch.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtSearch
            // 
            this.txtSearch.Font = new System.Drawing.Font("Tahoma", 10F);
            this.txtSearch.Location = new System.Drawing.Point(720, 10);
            this.txtSearch.Name = "txtSearch";
            this.txtSearch.Size = new System.Drawing.Size(240, 28);
            this.txtSearch.TabIndex = 0;
            this.txtSearch.TextChanged += new System.EventHandler(this.FilterControls_Changed);
            // 
            // cmbFilterType
            // 
            this.cmbFilterType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilterType.Font = new System.Drawing.Font("Tahoma", 10F);
            this.cmbFilterType.Location = new System.Drawing.Point(550, 10);
            this.cmbFilterType.Name = "cmbFilterType";
            this.cmbFilterType.Size = new System.Drawing.Size(160, 29);
            this.cmbFilterType.TabIndex = 1;
            this.cmbFilterType.SelectedIndexChanged += new System.EventHandler(this.FilterControls_Changed);
            // 
            // dataGridViewVouchers
            // 
            this.dataGridViewVouchers.AllowUserToAddRows = false;
            this.dataGridViewVouchers.AllowUserToDeleteRows = false;
            this.dataGridViewVouchers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewVouchers.BackgroundColor = System.Drawing.Color.White;
            this.dataGridViewVouchers.BorderStyle = System.Windows.Forms.BorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(42)))), ((int)(((byte)(57)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Tahoma", 9.5F);
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.dataGridViewVouchers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridViewVouchers.ColumnHeadersHeight = 38;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Tahoma", 9.5F);
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridViewVouchers.DefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridViewVouchers.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridViewVouchers.EnableHeadersVisualStyles = false;
            this.dataGridViewVouchers.Location = new System.Drawing.Point(0, 415);
            this.dataGridViewVouchers.MultiSelect = false;
            this.dataGridViewVouchers.Name = "dataGridViewVouchers";
            this.dataGridViewVouchers.ReadOnly = true;
            this.dataGridViewVouchers.RowHeadersVisible = false;
            this.dataGridViewVouchers.RowHeadersWidth = 51;
            this.dataGridViewVouchers.RowTemplate.Height = 34;
            this.dataGridViewVouchers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewVouchers.Size = new System.Drawing.Size(1100, 255);
            this.dataGridViewVouchers.TabIndex = 4;
            this.dataGridViewVouchers.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewVouchers_CellClick);
            // 
            // panelBottom
            // 
            this.panelBottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(250)))));
            this.panelBottom.Controls.Add(this.lblRecordCount);
            this.panelBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelBottom.Location = new System.Drawing.Point(0, 670);
            this.panelBottom.Name = "panelBottom";
            this.panelBottom.Size = new System.Drawing.Size(1100, 30);
            this.panelBottom.TabIndex = 5;
            // 
            // lblRecordCount
            // 
            this.lblRecordCount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRecordCount.Font = new System.Drawing.Font("Tahoma", 9F);
            this.lblRecordCount.ForeColor = System.Drawing.Color.DimGray;
            this.lblRecordCount.Location = new System.Drawing.Point(0, 0);
            this.lblRecordCount.Name = "lblRecordCount";
            this.lblRecordCount.Size = new System.Drawing.Size(1100, 30);
            this.lblRecordCount.TabIndex = 0;
            this.lblRecordCount.Text = "عدد السندات: 0";
            this.lblRecordCount.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // VouchersForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 19F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.dataGridViewVouchers);
            this.Controls.Add(this.panelBottom);
            this.Controls.Add(this.panelSearch);
            this.Controls.Add(this.panelButtons);
            this.Controls.Add(this.panelFields);
            this.Controls.Add(this.panelTitle);
            this.Font = new System.Drawing.Font("Tahoma", 9.5F);
            this.Name = "VouchersForm";
            this.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.Size = new System.Drawing.Size(1100, 700);
            this.panelTitle.ResumeLayout(false);
            this.panelFields.ResumeLayout(false);
            this.tableLayoutFields.ResumeLayout(false);
            this.tableLayoutFields.PerformLayout();
            this.panelButtons.ResumeLayout(false);
            this.panelSearch.ResumeLayout(false);
            this.panelSearch.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewVouchers)).EndInit();
            this.panelBottom.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        private System.Windows.Forms.Panel panelTitle;
        private System.Windows.Forms.Label lblTitle;

        private System.Windows.Forms.Panel panelFields;
        private System.Windows.Forms.TableLayoutPanel tableLayoutFields;

        private System.Windows.Forms.Label lblVoucherNumber;
        private System.Windows.Forms.TextBox txtVoucherNumber;

        private System.Windows.Forms.Label lblVoucherType;
        private System.Windows.Forms.ComboBox cmbVoucherType;

        private System.Windows.Forms.Label lblAmount;
        private System.Windows.Forms.TextBox txtAmount;

        private System.Windows.Forms.Label lblVoucherDate;
        private System.Windows.Forms.DateTimePicker dtpVoucherDate;

        private System.Windows.Forms.Label lblPartyName;
        private System.Windows.Forms.TextBox txtPartyName;

        private System.Windows.Forms.Label lblDescription;
        private System.Windows.Forms.TextBox txtDescription;

        private System.Windows.Forms.Label lblPaymentMethod;
        private System.Windows.Forms.ComboBox cmbPaymentMethod;

        private System.Windows.Forms.Label lblReferenceType;
        private System.Windows.Forms.ComboBox cmbReferenceType;

        private System.Windows.Forms.Label lblReferenceID;
        private System.Windows.Forms.TextBox txtReferenceID;

        private System.Windows.Forms.Label lblIsAutoGenerated;
        private System.Windows.Forms.CheckBox chkIsAutoGenerated;

        private System.Windows.Forms.Label lblNotes;
        private System.Windows.Forms.TextBox txtNotes;

        private System.Windows.Forms.Panel panelButtons;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnUpdate;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.Button btnClear;

        private System.Windows.Forms.Panel panelSearch;
        private System.Windows.Forms.Label lblSearch;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.ComboBox cmbFilterType;

        private System.Windows.Forms.DataGridView dataGridViewVouchers;

        private System.Windows.Forms.Panel panelBottom;
        private System.Windows.Forms.Label lblRecordCount;
    }
}
